"""Initial migration

Revision ID: 543d2f83f743
Revises: 
Create Date: 2025-02-01 19:19:53.174431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543d2f83f743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('FaultReports')
    op.drop_table('MeterReadings')
    with op.batch_alter_table('fault_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    with op.batch_alter_table('fault_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('MeterReadings',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reading', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('image', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='FK__MeterRead__user___73BA3083', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK__MeterRea__3213E83FC8BC7836')
    )
    op.create_table('FaultReports',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('location', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='FK__FaultRepo__user___76969D2E', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK__FaultRep__3213E83F8D7482F8')
    )
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phone', sa.NVARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('password', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__Users__3213E83F87969085')
    )
    # ### end Alembic commands ###
